(setq package-enable-at-startup nil)
(setq custom-file "~/.emacs.d/custom.el")
(setq gc-cons-threshold (* 32 1024 1024))
(setq inhibit-startup-message t)
(setq initial-scratch-message nil)
(setq initial-major-mode 'fundamental-mode)
(setq create-lockfiles nil)
(setq warning-minimum-level :error)
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))

(set-face-attribute 'default nil :height 120)
(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
