set-option -sg escape-time 5
setw -g mode-keys vi

unbind %
bind | split-window -h    # Prefix | to create vertical split
unbind '"'
bind - split-window -v    # Prefix - to create horizontal split
bind -r C-H resize-pane -L 1   # 5 px bigger to the left
bind -r C-J resize-pane -D 1   # 5 px bigger down
bind -r C-K resize-pane -U 1   # 5 px bigger up
bind -r C-L resize-pane -R 1   # 5 px bigger right
bind h select-pane -L 
bind j select-pane -D 
bind k select-pane -U 
bind l select-pane -R
bind-key X kill-pane

###########################
# Colors
###########################

set -g status-style fg=white,bg=colour235
set -g message-style fg=white,bold,bg=green
setw -g window-status-style fg=cyan,bg=colour235
setw -g window-status-current-style fg=white,bold,bg=red
set -g pane-border-style fg=colour240,bg=black
set -g pane-active-border-style fg=green,bg=black

###########################
# Plugins
###########################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'base16-project/base16-tmux'

set -g @colors-base16 'chalk'

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'

set -g default-terminal "tmux-direct"